// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18JIGjU1FGa4ECDt_RBXvGAn9JBN5mR0',
    appId: '1:743380669661:web:f981bd748da8a0fbd1f734',
    messagingSenderId: '743380669661',
    projectId: 'primeiro-projeto-onit',
    authDomain: 'primeiro-projeto-onit.firebaseapp.com',
    storageBucket: 'primeiro-projeto-onit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8r29bFHZ_ah8L0BjI-sb1eZPXd5hEBdY',
    appId: '1:743380669661:android:dbd99dab936c659bd1f734',
    messagingSenderId: '743380669661',
    projectId: 'primeiro-projeto-onit',
    storageBucket: 'primeiro-projeto-onit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATh399ZJsAQIy4pvQ82uqhXVOIwmmUmV4',
    appId: '1:743380669661:ios:efbec6e0f42fceffd1f734',
    messagingSenderId: '743380669661',
    projectId: 'primeiro-projeto-onit',
    storageBucket: 'primeiro-projeto-onit.appspot.com',
    iosClientId: '743380669661-9mobt8tg5he7i8tmo02sp5gj20hi2mfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
